In [1]:
from tensorflow.keras.preprocessing.text  import one_hot


In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
vocab_size=10000

In [5]:
## one Hot Representation
one_hot_repres = [one_hot(words , vocab_size) for words in sent]
one_hot_repres

[[5150, 9505, 8152, 5967],
 [5150, 9505, 8152, 2880],
 [5150, 6529, 8152, 457],
 [6700, 1542, 3528, 729, 3842],
 [6700, 1542, 3528, 729, 4806],
 [7481, 5150, 3460, 8152, 5470],
 [5334, 2055, 5940, 729]]

In [8]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [10]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repres , maxlen=sent_length , padding='pre')
print(embedded_docs)

[[   0    0    0    0 5150 9505 8152 5967]
 [   0    0    0    0 5150 9505 8152 2880]
 [   0    0    0    0 5150 6529 8152  457]
 [   0    0    0 6700 1542 3528  729 3842]
 [   0    0    0 6700 1542 3528  729 4806]
 [   0    0    0 7481 5150 3460 8152 5470]
 [   0    0    0    0 5334 2055 5940  729]]


In [11]:
## Feature Representation 
dim=10

In [20]:
model = Sequential()
model.add(Embedding(vocab_size , dim , input_length= sent_length))
model.compile(optimizer='adam' ,loss= 'mse')
model.build(input_shape=(None, sent_length))

In [21]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 317ms/step


array([[[ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.04164335, -0.04998294,  0.02520252,  0.02597498,
          0.00751032, -0.01311979,  0.03739539, -0.02788217,
          0.01006037, -0.00771926],
        [ 0.03842216,  0.01411073,  0.00415467, -0.01822408,
         -0.03086604, -0.02929652, -0.0132618 ,  0.02067343,
          0.02851783,  0.02998446],
        [ 0.0296515 ,  0.01327772,  0.00329541,  0.0

In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 5150, 9505, 8152, 5967], dtype=int32)

In [26]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 169ms/step


array([[[ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.0074388 , -0.00808672, -0.03521509,  0.02424374,
          0.01405051,  0.03241446, -0.02071987, -0.01322652,
         -0.02213373,  0.04407683],
        [ 0.04164335, -0.04998294,  0.02520252,  0.02597498,
          0.00751032, -0.01311979,  0.03739539, -0.02788217,
          0.01006037, -0.00771926],
        [ 0.03842216,  0.01411073,  0.00415467, -0.01822408,
         -0.03086604, -0.02929652, -0.0132618 ,  0.02067343,
          0.02851783,  0.02998446],
        [ 0.0296515 ,  0.01327772,  0.00329541,  0.0